# Generated by Django 3.2.9 on 2021-11-12 09:52

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=32,
                        validators=[api.validators.validate_string],
                    ),
                ),
                (
                    "an_achizitie",
                    models.PositiveIntegerField(
                        validators=[api.validators.validate_year]
                    ),
                ),
                ("nr_km", models.PositiveIntegerField()),
                (
                    "suma_manopera",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[api.validators.validate_positive],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nume",
                    models.CharField(
                        max_length=32,
                        validators=[api.validators.validate_string],
                    ),
                ),
                (
                    "prenume",
                    models.CharField(
                        max_length=32,
                        validators=[api.validators.validate_string],
                    ),
                ),
                (
                    "CNP",
                    models.PositiveIntegerField(
                        unique=True, validators=[api.validators.validate_cnp]
                    ),
                ),
                (
                    "data_nasterii",
                    models.DateField(
                        validators=[api.validators.validate_date]
                    ),
                ),
                ("data_inregistrarii", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suma_piese",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[api.validators.stringvalidator],
                    ),
                ),
                (
                    "suma_manopera",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            api.validators.stringvalidator,
                            api.validators.validate_positive,
                        ],
                    ),
                ),
                ("data_si_ora", models.DateTimeField(auto_now_add=True)),
                (
                    "id_client_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.clientcard",
                    ),
                ),
                (
                    "id_masina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cars",
                    ),
                ),
            ],
        ),
    ]
