# Generated by Django 3.2.9 on 2021-11-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20211113_0138"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="suma_manopera",
        ),
    ]
