# Generated by Django 3.2.9 on 2021-11-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_cars_suma_manopera"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="suma_manopera",
        ),
    ]
