# Generated by Django 3.2.9 on 2021-11-13 01:20

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_cars_suma_manopera"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcard",
            name="reducere_totala",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    api.validators.stringvalidator,
                    api.validators.validate_positive,
                ],
            ),
            preserve_default=False,
        ),
    ]
