# Generated by Django 3.2.9 on 2021-11-13 02:22

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_transactions_id_masina"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="manopera",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    api.validators.stringvalidator,
                    api.validators.validate_positive,
                ],
            ),
        ),
    ]
