# Generated by Django 3.2.9 on 2021-11-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_auto_20211113_0424"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cars",
            new_name="Car",
        ),
        migrations.RenameModel(
            old_name="Transactions",
            new_name="Transaction",
        ),
    ]
