# Generated by Django 3.2.9 on 2021-11-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_auto_20211113_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id_client_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="api.clientcard",
            ),
        ),
    ]
