# Generated by Django 3.2.9 on 2021-11-13 17:04

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_transaction_id_client_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reducere_manopera",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[
                    api.validators.stringvalidator,
                    api.validators.validate_positive,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reducere_piese",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[
                    api.validators.stringvalidator,
                    api.validators.validate_positive,
                ],
            ),
        ),
    ]
